### ISSUE TITLE
renovate.json config doesn't detect backwards incompatible changes correctly

### ISSUE THREAD

**Issue by brikis98** [gruntwork-io/bash-commons#25]
The template we're using to render parts of the PR body _always_ say the change is backwards incompatible, even for patch version bumps. Must be some issue in the `renovate.json`.

**Comment by yorinasub17** [comment]
@brikis98 Did you intend to file this here, in `bash-commons`?

**Comment by brikis98** [comment]
lol, no, no I did not 😁 

No clue how that happened, closing this issue and will re-open in proper repo 🤦
