### ISSUE TITLE
bash-commons does not check which version of IMDS is running

### ISSUE THREAD

**Issue by justin-octo** [gruntwork-io/bash-commons#57]
Bash Commons is called by nearly every other module.  One of the essential tasks other modules rely on is returning the Region.  Bash-commons gets this from the instance metadata using IMDS.  Unfortunately, the scripts here are missing logic to first detect which version of IMDS is allowed.

Instead the scripts here default to IMDSv1 unless v2 is passed in via a environment variable `GRUNTWORK_BASH_COMMONS_IMDS_VERSION="2"`

While allowing modules to specific which IMDS version is good, depending on this is not.  I recommend the aws.sh script be updated to check which version of IMDS is enabled (if any) before trying to get the Region from the instance metadata.

**Describe the bug**
Many modules that call bash-commons fail if IMDSv2 is set to required.

**To Reproduce**
Configure a Packer Build to require IMDSv2 and watch it break.  Run a Terraform/Terragrunt Apply with IMDSv2 set as "required" and watch it break. 

**Expected behavior**
bash-commons scripts should verify which version of IMDS is available on the instance before checking the metadata on an instance.

**Nice to have**
- [ ] Terminal output
- [ ] Screenshots

**Additional context**
Some work-arounds for another module "terraform-aws-monitoring" are presented here:
https://github.com/gruntwork-io/terraform-aws-monitoring/pull/341

**Comment by gcagle3** [comment]
This has been released in [v0.2.0](https://github.com/gruntwork-io/bash-commons/releases/tag/v0.2.0).
