### ISSUE TITLE
Error if IMDS Version not set

### ISSUE THREAD

**Issue by justin-octo** [gruntwork-io/bash-commons#67]
The IF statement in the aws.sh script does not handle it well if certain variables are not set.  This is not noticable until the aws.sh is run.

See the comments here for more info.
https://github.com/gruntwork-io/terraform-aws-monitoring/issues/340

**Nice to have**
- [ ] Terminal output
- [ ] Screenshots

**Additional context**

**Comment by justin-octo** [comment]
There is a workaround for this by setting `set +u` before any bash-commons script is set, and then optionally setting it back to `set -u` depending on your need.

**Comment by justin-octo** [comment]
Some of the functions, like assert_not_empty, does not check for empty variables well and thus errors if something is not set (i.e. no "reason" or an empty second variable is sent to the function).
Comment/workaround above fixes this.

**Comment by gcagle3** [comment]
This should be fixed in [v0.2.2](https://github.com/gruntwork-io/bash-commons/releases/tag/v0.2.2). Please re-open this issue if this version does not resolve your original issue. Thanks!
