### ISSUE TITLE
Local readonly variables not declared correctly

### ISSUE THREAD

**Issue by brikis98** [gruntwork-io/bash-commons#9]
We currently use `local readonly` to declare local, read-only variables. It turns out that this [is not the right way to do it](https://stackoverflow.com/a/45409823/483528). The proper way is:

```bash
local -r var="$1"
```

For arrays, you need:

```bash
local -ar var=(foo bar)
```

**Comment by housni** [comment]
I believe this is resolved in #8.

**Comment by brikis98** [comment]
You're right! This was fixed by https://github.com/gruntwork-io/bash-commons/pull/11. Finally closing :)
